# Generated by Django 4.2.24 on 2025-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='student_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
