# Generated by Django 4.2.24 on 2025-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_category_parent_id_alter_category_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='category',
            name='student_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('student_id', 'parent_id')},
        ),
    ]
