# Generated by Django 4.2.24 on 2025-11-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_category_parent_id_alter_category_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_face',
            field=models.ImageField(blank=True, null=True, upload_to='faces/parents/'),
        ),
        migrations.AddField(
            model_name='category',
            name='student_face',
            field=models.ImageField(blank=True, null=True, upload_to='faces/students/'),
        ),
    ]
