# Generated by Django 4.2.24 on 2025-11-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_id', models.CharField(max_length=20, unique=True)),
                ('parent_name', models.CharField(max_length=100)),
            ],
        ),
    ]
