# Generated by Django 4.2.24 on 2025-11-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_category_parent_face_category_student_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='student_face',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_face',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
