# Generated by Django 4.2.24 on 2025-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_category_student_face_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_face',
            field=models.URLField(max_length=500),
        ),
    ]
